name: .jpg sorter

on:
  pull_request:
    paths:
      - '**.jpg'
  
  push:
    paths:
      - '**.jpg'

jobs:
  sort-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Move .jpg files to images folder
        run: |
            touch /Images
            mv *.jpg Images

      - name: Commit changes
        run: |
          git config user.name 'DanielBrett'
          git config user.email 'dbrett@brocku.ca'
          git add .
          git commit -m "Image Sorter Run"
          git push
            
