name: File sorter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  sort-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: sort images
        run: |
            echo starting image move
            mv *.jpg Images

      
      - name: Commit changes
        run: |
          git config --global user.name 'DanielBrett'
          git config --global user.email 'dbrett@brocku.ca'
          git add -A
          git commit -m "Image Sorter Run"
          git push
            
