name: .jpg sorter

on:
  pull_request:
    paths:
      - '**.jpg'

jobs:
  sort-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Move .jpg files to images folder
        run:
            mv *.jpg Images

      - name: Commit changes
        run: |
          git config --global user.name 'DanielBrett'
          git config --global user.email 'dbrett@brocku.ca'
          git add -A
          git commit -m "Image Sorter Run"
          git push
            
