name: File sorter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  sort-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: sort images
        run: |
            pwd
            ls
            mv *.jpg Images
            echo action taken
            ls
            
      - name: Commit changes
        run:
          git push
            
